### ISSUE TITLE
wget command error..

### ISSUE THREAD

**Issue by steve0hh** [kswedberg/jquery-tmbundle#13]
mkdir -p ~/Library/Application\ Support/TextMate/Bundles
cd ~/Library/Application\ Support/TextMate/Bundles
wget http://github.com/kswedberg/jquery-tmbundle/tarball/master
tar zxf kswedberg-jquery-tmbundle_.tar.gz
rm kswedberg-jquery-tmbundle_.tar.gz
mv kswedberg-jquery-tmbundle\* "JavaScript jQuery.tmbundle"
osascript -e 'tell app "TextMate" to reload bundles'

wget command not found in my max osx computer. i'm running version 10.6.7.. i manually downloaded the file and moved it to the bundles folder and ran the command.. =) but i believe the curl command would achieve the same thing too..

**Comment by svnlto** [comment]
you could use curl instead, it ships with the mac.

**Comment by steve0hh** [comment]
Yes. I know. Not too easy to install for a new mac user like me. =)
