### ISSUE TITLE
Tab triggers doesn't seem to work

### ISSUE THREAD

**Issue by Aberen** [kswedberg/jquery-tmbundle#15]
I've installed the bundle and it loads up fine... But the tab triggers for the jQuery bundle don't seem to work  

Any ideas? 

**edit**: This seems to be the case for both my Macbook Pro and Mac Mini

**Comment by kswedberg** [comment]
Make sure the Language is set to jQuery (JavaScript). It might be set to JavaScript instead. You can set the Language from the status bar at the bottom of the TextMate window. Look for the "L". Or, press `Control + Option + Shift + J`. Then choose jQuery (JavaScript) from the list that appears. TextMate should remember your choice the next time you open a .js file.

Let me know if that doesn't work.

**Comment by Aberen** [comment]
You are a scholar and a life savior sir. Totally works now, thanks!

**Comment by kswedberg** [comment]
glad to hear it's working for you. enjoy!
