### ISSUE TITLE
Snippets / plugin (method extras) - Cannot read property 'defaults' of undefined

### ISSUE THREAD

**Issue by jorgecasar** [kswedberg/jquery-tmbundle#18]
I got an error

_Uncaught TypeError: Cannot read property 'defaults' of undefined_

in line 79:

_opts = \$.extend( true, {}, \$.fn.cluetip.defaults, opts, options || {} );_

and I solve it by putting _$1_ instead of _cluetip_ because of line 105:

\$.extend(\$.fn.$1, {
    defaults: settings
  });

Thanks!

**Comment by kswedberg** [comment]
thanks a lot for the report!

**Comment by jorgecasar** [comment]
You are welcome, thanks for you code and your fast response.

Keep in touch.
