### ISSUE TITLE
TextMate v1631 -- JQuery Bundle doesn't seem to work at all

### ISSUE THREAD

**Issue by hiediutley** [kswedberg/jquery-tmbundle#20]
I just followed your installation instructions and cloned your repo and reloaded my bundles. I see the JQuery bundle in the list and I can click on the menu items and it inserts the snippets but if I am just trying to type the shortcuts then nothing happens. 

I am on TextMate Version 1.5.10 (1631). Any ideas?

**Comment by kswedberg** [comment]
When you're in the file, you need to change the language (click the "L" popup list in the status bar) to "jQuery (JavaScript)." If you did that and it still isn't working, let me know.

**Comment by hiediutley** [comment]
That worked. Thanks!
