### ISSUE TITLE
Convert Filenames to Windows supported ones

### ISSUE THREAD

**Issue by ProLoser** [kswedberg/jquery-tmbundle#4]
E TextEditor for windows supports TextMate bundles. I go back and forth from windows and mac when I work, but unfortunately I cannot clone this repo properly because of the : (colon) in some of the filenames under Snippets. It would be nice if this bundle was made compatible with windows/e-texteditor.

**Comment by kswedberg** [comment]
I just updated the bundle in an attempt to get it to work with E TextEditor, though I can't test it. If it still doesn't doesn't work, feel free to open another issue. Thanks!
