### ISSUE TITLE
Bundle deos not sem active in html files

### ISSUE THREAD

**Issue by rpechayr** [kswedberg/jquery-tmbundle#5]
I am trying to use your bundle and it does not do anything on a html file, when coding a <script></script> tag. Is it supposed to ?

**Comment by svnlto** [comment]
this might help.

http://github.com/kswedberg/jquery-tmbundle/wiki/getting-jquery-bundle-to-work-within-script-tags-embedded-in-html

**Comment by 01iv3r** [comment]
Dude, thank you! You're awesome :)
This works great with the Zen Coding.
