### ISSUE TITLE
changing scope selector

### ISSUE THREAD

**Issue by pulse00** [kswedberg/jquery-tmbundle#6]
i noticed that all snippets have the scope selector set to "source.js.jquery". When opening *.js files, textmate does not provide those jquery snippets, unless i manually set the language to "jquery (Javascript)". Is this behavior intended, or is it possible to automatically use the jquery scope for *.js files?

**Comment by kswedberg** [comment]
TextMate should remember your previous language choice the next time you open a .js file. So if you change it to jQuery (JavaScript) for one .js file, subsequent .js files should open with jQuery (JavaScript) when you open them.

**Comment by luksak** [comment]
i tried to change the scope to source.js. but if i open a .php file which contains JS TM crashes. would be nice to be able to use this bundle everywhere where i can use JS since all of my JS contains jQuery.
