### ISSUE TITLE
Not working inside script tags on (scope HTML)

### ISSUE THREAD

**Issue by 01iv3r** [kswedberg/jquery-tmbundle#7]
This bundle's snippets do not work from inside script tags on HTML pages. 

see: https://github.com/subtleGradient/javascript.tmbundle

**Comment by kswedberg** [comment]
It does work, but you have to do a little extra fiddling. See http://wiki.github.com/kswedberg/jquery-tmbundle/getting-jquery-bundle-to-work-within-script-tags-embedded-in-html
