### ISSUE TITLE
map snippet has elem, index reversed

### ISSUE THREAD

**Issue by krismolendyke** [kswedberg/jquery-tmbundle#8]
http://api.jquery.com/jQuery.map specifies:
jQuery.map( array, callback(elementOfArray, indexInArray) )

and the snippet is currently:

.map(function(index, elem) {
  ${1:return ${2:something};}

I'd request a placeholder for specifying the array argument, as well, please!  Thanks!

**Comment by kswedberg** [comment]
sorry about that. actually, I didn't have a snippet for jQuery.map, just for $.map, so when TextMate saw the ".map" part, it just used the snippet for that (http://api.jquery.com/map/).

I've updated the bundle to include a "jQuery." snippet for every "$." snippet, so if you pull down the latest, it should work now for you.

**Comment by krismolendyke** [comment]
Great, thanks!
